name: $(Build.BuildId) - main

trigger:
  batch: true
  branches:
    include:
      - main
      - refs/tags/v*

stages:
- stage: Build
  jobs:
  - job: macOS
    condition: eq(variables['build.sourceBranch'], 'refs/heads/main')
    pool:
      vmImage: macOS-latest
    variables:
      CACHE_FOLDER: $(Pipeline.Workspace)/cache
    steps:
    - template: .ci/build-platform.yml
    - template: .ci/build-docs.yml
    - template: .ci/utils/prepare-cache.yml

- stage: Publish_docs
  displayName: Publish documentation
  dependsOn: [Build]
  jobs:
  - deployment: Publish_docs
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    displayName: Publish docs to GitHub
    environment: gh-pages
    pool:
      vmImage: ubuntu-16.04
    strategy:
      runOnce:
        deploy:
          steps:
            - template: .ci/publish-api-docs.yml

- stage: Publish_npm
  displayName: Publish release to npm
  dependsOn: [Build]
  jobs:
  - job: Publish_npm
    condition: startsWith(variables['build.sourceBranch'], 'refs/tags/v')
    steps:
    - task: Npm@1
      inputs:
        command: publish
        publishEndpoint: NPM
